### ISSUE TITLE
4:3 output possible?

### ISSUE THREAD

**Issue by TwoLeaves** [usineur/sdlpal#6]
Hi, is it possible to display the game in a 4:3 aspect ratio like the original would have been? I tried to play around with WindowHeight/Width, TextureHeight/Width and KeepAspectRatio in the config (as well as tinkering with pal_config.h) but couldn't produce anything other than a 16:9 output. I'm using the latest Switch port (1.0-nx). Thanks.

**Comment by usineur** [comment]
It's not possible with current Switch version. Maybe I will add it in a next relase.

**Comment by palxex** [comment]
Seems the latest release already able to make KeepAspectRatio work, only need the user to specify correct WindowWidth/WindowHeight value in sdlpal.cfg. Since some unknown implementation-based problem in DevKitPro's Homebrew SDL, the KeepAspectRatio  code only works under the current( when the nro launched) native resolution; for handheld mode it's 720P, and for docked mode it's 1080P. (Thanks to the long-lived resizing bug in the same SDL implementation, we dont need to handle dynamic resolution switching, at least for now. LOL).
Since predicating the resolution and modify the cfg everytime will be a totally mess, I've made a simple patch for making KeepAspectRatio always work, in the cost of WindowWidth/Height in cfg be ignored in that case.
```
diff --git a/video_glsl.c b/video_glsl.c
index 83650fe7..201af649 100644
--- a/video_glsl.c
+++ b/video_glsl.c
@@ -928,6 +928,13 @@ int get_SDL_GLAttribute(SDL_GLattr attr) {
     return orig_value;
 }
 
+void UseActualResolution() {
+    SDL_DisplayMode DM;
+    SDL_GetCurrentDisplayMode(0, &DM);
+    gConfig.dwScreenWidth = DM.w;
+    gConfig.dwScreenHeight = DM.h;
+}
+
 void VIDEO_GLSL_Init() {
     int orig_major, orig_minor, orig_profile;
     SDL_GL_GetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, &orig_major);
@@ -947,7 +954,15 @@ void VIDEO_GLSL_Init() {
 #endif
 
     Uint32 flags = PAL_VIDEO_INIT_FLAGS | (gConfig.fFullScreen ? SDL_WINDOW_BORDERLESS : 0) | SDL_WINDOW_OPENGL;
-    
+
+    #ifdef __SWITCH__
+    //
+    // since KeepAspectRatio on DKP SDL not work well with non-native resolution
+    //
+    if (gConfig.fKeepAspectRatio)
+        UseActualResolution();
+    #endif
+
     UTIL_LogOutput(LOGLEVEL_DEBUG, "requesting to create window with flags: %s %s profile latest available\n", SDL_GetHint( SDL_HINT_RENDER_DRIVER ),  get_gl_profile(get_SDL_GLAttribute(SDL_GL_CONTEXT_PROFILE_MASK)));
 #ifndef __SWITCH__
     gpWindow = SDL_CreateWindow("Pal", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, gConfig.dwScreenWidth, gConfig.dwScreenHeight, flags);
```

**Comment by usineur** [comment]
Fine, can you make a PR ?
